package com.albertattard.polls.service

import com.albertattard.polls.helpers.CreatePollHelper
import com.albertattard.polls.helpers.DatabaseHelper
import io.kotlintest.shouldBe
import io.kotlintest.specs.StringSpec
import io.micronaut.test.annotation.MicronautTest
import org.jetbrains.exposed.sql.Database

@MicronautTest
class CreatePollDefaultServiceTest(
    private val database: Database
) : StringSpec({
    "should create the poll and return the share link generated by the greeting service" {
        val create = CreatePollHelper.sample()
        val service = PollDefaultService(database)
        val pollId = service.create(create)

        /* Verify that the poll is in the database */
        DatabaseHelper.withPoll(database, pollId) {
            it["caption"] shouldBe create.caption
        }

        create.questions.forEachIndexed { questionIndex, question ->
            val questionId = DatabaseHelper.withQuestion(database, pollId, questionIndex) {
                it["pollId"] shouldBe pollId
                it["index"] shouldBe questionIndex
                it["question"] shouldBe question.text
            }

            question.possibleAnswers.forEachIndexed { answerIndex, possibleAnswer ->
                DatabaseHelper.withPossibleAnswer(database, questionId, answerIndex) {
                    it["pollId"] shouldBe pollId
                    it["questionId"] shouldBe questionId
                    it["index"] shouldBe answerIndex
                    it["possibleAnswer"] shouldBe possibleAnswer.text
                }
            }
        }
    }
})
