package com.albertattard.polls.application

import com.albertattard.polls.model.CreatePoll
import com.albertattard.polls.model.CreatedPoll
import com.albertattard.polls.model.PossibleAnswer
import com.albertattard.polls.model.Question
import io.kotlintest.matchers.string.shouldMatch
import io.kotlintest.shouldNotBe
import io.kotlintest.specs.StringSpec
import io.micronaut.http.HttpRequest
import io.micronaut.http.client.RxHttpClient
import io.micronaut.http.client.annotation.Client
import io.micronaut.test.annotation.MicronautTest

@MicronautTest
class PollControllerEndToEndTest(
    @Client("/poll") private val client: RxHttpClient
) : StringSpec({
    "should create the poll and return the share link generated by the greeting service" {
        val create = CreatePoll(
            caption = "Test Poll",
            questions = listOf(
                Question(possibleAnswers = listOf(PossibleAnswer("Sample question 1")))
            )
        )

        val response = client.toBlocking().exchange(HttpRequest.POST("/create", create), CreatedPoll::class.java)
        println("Created: ${response.body()}")
        val created = response.body()
        created shouldNotBe null
        created?.link shouldNotBe null
        created?.link shouldMatch "/poll/[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}"
    }
})
